### ISSUE TITLE
Change documentation to usage of npx

### ISSUE THREAD

**Issue by SheepFromHeaven** [biotope/biotope-cli#9]
In future we should use npx to omit version problems. Add this to the readme.

**Comment by jurekbarth** [comment]
@SheepFromHeaven anyway i would like to add some kind of global version file somewhere in your home directory. So the generator periodically checks it's version, without disrupting the workflow. Also i would suggest adding a log with the current version (that may be already the case?) and a warning if you're somehow not on the latest version. My last point should not fail though, because sometimes i may want to use a specific version 👍
